ExperienceGain:
  player_slay: 5
  monster_slay: 5
  fish: 5
  enchant: 5
  level_up: 5
  first_biome_enter : 5
  block_break:
    diamond_ore: 5
    emerald_ore: 10
LevelFormula: # f(x) = a*x^3 + b*x^2 + c*x
  a: 1.0
  b: 1.0
  c: 20.0
DimensionLock:
  nether: 5
  end: 10
